[theme]
primaryColor = "#2E5FF3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"



[server]
headless = false
port = 8501

[browser]
gatherUsageStats = false
